name: microsite
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.03942652
color:
  saturation: 0.5281276809982955
  brandStrength: 1
  rhythmicContrast: 0.5836242865771055
  brandColors:
    - '#040403'
    - '#313138'
    - '#EACFCF'
    - '#645D4C'
    - '#92776E'
  lightness: 0.7576925272587687
purpose: []
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
typography_spectrum: 0
